/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as GeneralRouteRouteImport } from './routes/_general/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as ApiChatRouteRouteImport } from './routes/api/chat/route'
import { Route as ApiProxyImageRouteImport } from './routes/api/proxy-image'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ArticleSlugRouteImport } from './routes/article/$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAlbumsRouteRouteImport } from './routes/dashboard/albums/route'
import { Route as DashboardImagesRouteRouteImport } from './routes/dashboard/images/route'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as ChatChatIndexRouteImport } from './routes/_chat/chat/index'
import { Route as ChatChatChatboxRouteRouteImport } from './routes/_chat/chat/_chatbox/route'
import { Route as GeneralAboutIndexRouteImport } from './routes/_general/about/index'
import { Route as GeneralArticleIndexRouteImport } from './routes/_general/article.index'
import { Route as GeneralBlogIndexRouteImport } from './routes/_general/blog.index'
import { Route as GeneralBlogpostsIndexRouteImport } from './routes/_general/blogposts.index'
import { Route as GeneralEnvologsIndexRouteImport } from './routes/_general/envologs.index'
import { Route as GeneralPostIndexRouteImport } from './routes/_general/post.index'
import { Route as GeneralUserUserIdRouteImport } from './routes/_general/user/$userId'
import { Route as AlbumAlbumIdIndexRouteImport } from './routes/album/$albumId.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as BlogSlugIndexRouteImport } from './routes/blog/$slug.index'
import { Route as BlogpostsSlugIndexRouteImport } from './routes/blogposts/$slug.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardAlbumsIndexRouteImport } from './routes/dashboard/albums/index'
import { Route as DashboardBlogIndexRouteImport } from './routes/dashboard/blog/index'
import { Route as DashboardImageUploadIndexRouteImport } from './routes/dashboard/image-upload/index'
import { Route as DashboardImagesIndexRouteImport } from './routes/dashboard/images/index'
import { Route as DashboardPostIndexRouteImport } from './routes/dashboard/post/index'
import { Route as DashboardQuranTrackerIndexRouteImport } from './routes/dashboard/quran-tracker/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardTaskTrackerIndexRouteImport } from './routes/dashboard/task-tracker/index'
import { Route as DashboardTaskTrackerTaskListIdRouteImport } from './routes/dashboard/task-tracker/$taskListId'
import { Route as EnvologsSlugIndexRouteImport } from './routes/envologs/$slug.index'
import { Route as PostPostIdIndexRouteImport } from './routes/post/$postId.index'
import { Route as DashboardAlbumsAlbumIdIndexRouteImport } from './routes/dashboard/albums/$albumId.index'
import { Route as DashboardBlogSlugIndexRouteImport } from './routes/dashboard/blog/$slug.index'
import { Route as DashboardBlogCreateBlogIndexRouteImport } from './routes/dashboard/blog/create-blog/index'
import { Route as DashboardBlogMdEditorIndexRouteImport } from './routes/dashboard/blog/md-editor/index'
import { Route as ChatChatChatboxAdapterIndexRouteImport } from './routes/_chat/chat/_chatbox/$adapter.index'
import { Route as DashboardBlogSlugEditIndexRouteImport } from './routes/dashboard/blog/$slug.edit.index'
import { Route as DashboardBlogSlugEditMdEditorRouteImport } from './routes/dashboard/blog/$slug.edit.md-editor'
import { Route as ChatChatChatboxAdapterChatIdIndexRouteImport } from './routes/_chat/chat/_chatbox/$adapter.$chatId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralRouteRoute = GeneralRouteRouteImport.update({
  id: '/_general',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRouteRoute = ApiChatRouteRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyImageRoute = ApiProxyImageRouteImport.update({
  id: '/api/proxy-image',
  path: '/api/proxy-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAlbumsRouteRoute = DashboardAlbumsRouteRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardImagesRouteRoute = DashboardImagesRouteRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ChatChatIndexRoute = ChatChatIndexRouteImport.update({
  id: '/_chat/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatChatboxRouteRoute = ChatChatChatboxRouteRouteImport.update({
  id: '/_chat/chat/_chatbox',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralAboutIndexRoute = GeneralAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => GeneralRouteRoute,
} as any)
const GeneralArticleIndexRoute = GeneralArticleIndexRouteImport.update({
  id: '/article/',
  path: '/article/',
  getParentRoute: () => GeneralRouteRoute,
} as any)
const GeneralBlogIndexRoute = GeneralBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => GeneralRouteRoute,
} as any)
const GeneralBlogpostsIndexRoute = GeneralBlogpostsIndexRouteImport.update({
  id: '/blogposts/',
  path: '/blogposts/',
  getParentRoute: () => GeneralRouteRoute,
} as any)
const GeneralEnvologsIndexRoute = GeneralEnvologsIndexRouteImport.update({
  id: '/envologs/',
  path: '/envologs/',
  getParentRoute: () => GeneralRouteRoute,
} as any)
const GeneralPostIndexRoute = GeneralPostIndexRouteImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => GeneralRouteRoute,
} as any)
const GeneralUserUserIdRoute = GeneralUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => GeneralRouteRoute,
} as any)
const AlbumAlbumIdIndexRoute = AlbumAlbumIdIndexRouteImport.update({
  id: '/album/$albumId/',
  path: '/album/$albumId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugIndexRoute = BlogSlugIndexRouteImport.update({
  id: '/blog/$slug/',
  path: '/blog/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogpostsSlugIndexRoute = BlogpostsSlugIndexRouteImport.update({
  id: '/blogposts/$slug/',
  path: '/blogposts/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAlbumsIndexRoute = DashboardAlbumsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAlbumsRouteRoute,
} as any)
const DashboardBlogIndexRoute = DashboardBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardImageUploadIndexRoute =
  DashboardImageUploadIndexRouteImport.update({
    id: '/image-upload/',
    path: '/image-upload/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardImagesIndexRoute = DashboardImagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardImagesRouteRoute,
} as any)
const DashboardPostIndexRoute = DashboardPostIndexRouteImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardQuranTrackerIndexRoute =
  DashboardQuranTrackerIndexRouteImport.update({
    id: '/quran-tracker/',
    path: '/quran-tracker/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTaskTrackerIndexRoute =
  DashboardTaskTrackerIndexRouteImport.update({
    id: '/task-tracker/',
    path: '/task-tracker/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTaskTrackerTaskListIdRoute =
  DashboardTaskTrackerTaskListIdRouteImport.update({
    id: '/task-tracker/$taskListId',
    path: '/task-tracker/$taskListId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const EnvologsSlugIndexRoute = EnvologsSlugIndexRouteImport.update({
  id: '/envologs/$slug/',
  path: '/envologs/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdIndexRoute = PostPostIdIndexRouteImport.update({
  id: '/post/$postId/',
  path: '/post/$postId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAlbumsAlbumIdIndexRoute =
  DashboardAlbumsAlbumIdIndexRouteImport.update({
    id: '/$albumId/',
    path: '/$albumId/',
    getParentRoute: () => DashboardAlbumsRouteRoute,
  } as any)
const DashboardBlogSlugIndexRoute = DashboardBlogSlugIndexRouteImport.update({
  id: '/blog/$slug/',
  path: '/blog/$slug/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBlogCreateBlogIndexRoute =
  DashboardBlogCreateBlogIndexRouteImport.update({
    id: '/blog/create-blog/',
    path: '/blog/create-blog/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBlogMdEditorIndexRoute =
  DashboardBlogMdEditorIndexRouteImport.update({
    id: '/blog/md-editor/',
    path: '/blog/md-editor/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ChatChatChatboxAdapterIndexRoute =
  ChatChatChatboxAdapterIndexRouteImport.update({
    id: '/$adapter/',
    path: '/$adapter/',
    getParentRoute: () => ChatChatChatboxRouteRoute,
  } as any)
const DashboardBlogSlugEditIndexRoute =
  DashboardBlogSlugEditIndexRouteImport.update({
    id: '/blog/$slug/edit/',
    path: '/blog/$slug/edit/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBlogSlugEditMdEditorRoute =
  DashboardBlogSlugEditMdEditorRouteImport.update({
    id: '/blog/$slug/edit/md-editor',
    path: '/blog/$slug/edit/md-editor',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ChatChatChatboxAdapterChatIdIndexRoute =
  ChatChatChatboxAdapterChatIdIndexRouteImport.update({
    id: '/$adapter/$chatId/',
    path: '/$adapter/$chatId/',
    getParentRoute: () => ChatChatChatboxRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/api/chat': typeof ApiChatRouteRoute
  '/dashboard/albums': typeof DashboardAlbumsRouteRouteWithChildren
  '/dashboard/images': typeof DashboardImagesRouteRouteWithChildren
  '/api/proxy-image': typeof ApiProxyImageRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/chat': typeof ChatChatChatboxRouteRouteWithChildren
  '/user/$userId': typeof GeneralUserUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/task-tracker/$taskListId': typeof DashboardTaskTrackerTaskListIdRoute
  '/login/': typeof AuthLoginIndexRoute
  '/chat/': typeof ChatChatIndexRoute
  '/about/': typeof GeneralAboutIndexRoute
  '/article/': typeof GeneralArticleIndexRoute
  '/blog/': typeof GeneralBlogIndexRoute
  '/blogposts/': typeof GeneralBlogpostsIndexRoute
  '/envologs/': typeof GeneralEnvologsIndexRoute
  '/post/': typeof GeneralPostIndexRoute
  '/album/$albumId/': typeof AlbumAlbumIdIndexRoute
  '/blog/$slug/': typeof BlogSlugIndexRoute
  '/blogposts/$slug/': typeof BlogpostsSlugIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/albums/': typeof DashboardAlbumsIndexRoute
  '/dashboard/blog/': typeof DashboardBlogIndexRoute
  '/dashboard/image-upload/': typeof DashboardImageUploadIndexRoute
  '/dashboard/images/': typeof DashboardImagesIndexRoute
  '/dashboard/post/': typeof DashboardPostIndexRoute
  '/dashboard/quran-tracker/': typeof DashboardQuranTrackerIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/task-tracker/': typeof DashboardTaskTrackerIndexRoute
  '/envologs/$slug/': typeof EnvologsSlugIndexRoute
  '/post/$postId/': typeof PostPostIdIndexRoute
  '/dashboard/albums/$albumId/': typeof DashboardAlbumsAlbumIdIndexRoute
  '/dashboard/blog/$slug/': typeof DashboardBlogSlugIndexRoute
  '/dashboard/blog/create-blog/': typeof DashboardBlogCreateBlogIndexRoute
  '/dashboard/blog/md-editor/': typeof DashboardBlogMdEditorIndexRoute
  '/dashboard/blog/$slug/edit/md-editor': typeof DashboardBlogSlugEditMdEditorRoute
  '/chat/$adapter/': typeof ChatChatChatboxAdapterIndexRoute
  '/dashboard/blog/$slug/edit/': typeof DashboardBlogSlugEditIndexRoute
  '/chat/$adapter/$chatId/': typeof ChatChatChatboxAdapterChatIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRouteRoute
  '/api/proxy-image': typeof ApiProxyImageRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/chat': typeof ChatChatIndexRoute
  '/user/$userId': typeof GeneralUserUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/task-tracker/$taskListId': typeof DashboardTaskTrackerTaskListIdRoute
  '/login': typeof AuthLoginIndexRoute
  '/about': typeof GeneralAboutIndexRoute
  '/article': typeof GeneralArticleIndexRoute
  '/blog': typeof GeneralBlogIndexRoute
  '/blogposts': typeof GeneralBlogpostsIndexRoute
  '/envologs': typeof GeneralEnvologsIndexRoute
  '/post': typeof GeneralPostIndexRoute
  '/album/$albumId': typeof AlbumAlbumIdIndexRoute
  '/blog/$slug': typeof BlogSlugIndexRoute
  '/blogposts/$slug': typeof BlogpostsSlugIndexRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/albums': typeof DashboardAlbumsIndexRoute
  '/dashboard/blog': typeof DashboardBlogIndexRoute
  '/dashboard/image-upload': typeof DashboardImageUploadIndexRoute
  '/dashboard/images': typeof DashboardImagesIndexRoute
  '/dashboard/post': typeof DashboardPostIndexRoute
  '/dashboard/quran-tracker': typeof DashboardQuranTrackerIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/task-tracker': typeof DashboardTaskTrackerIndexRoute
  '/envologs/$slug': typeof EnvologsSlugIndexRoute
  '/post/$postId': typeof PostPostIdIndexRoute
  '/dashboard/albums/$albumId': typeof DashboardAlbumsAlbumIdIndexRoute
  '/dashboard/blog/$slug': typeof DashboardBlogSlugIndexRoute
  '/dashboard/blog/create-blog': typeof DashboardBlogCreateBlogIndexRoute
  '/dashboard/blog/md-editor': typeof DashboardBlogMdEditorIndexRoute
  '/dashboard/blog/$slug/edit/md-editor': typeof DashboardBlogSlugEditMdEditorRoute
  '/chat/$adapter': typeof ChatChatChatboxAdapterIndexRoute
  '/dashboard/blog/$slug/edit': typeof DashboardBlogSlugEditIndexRoute
  '/chat/$adapter/$chatId': typeof ChatChatChatboxAdapterChatIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_general': typeof GeneralRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/api/chat': typeof ApiChatRouteRoute
  '/dashboard/albums': typeof DashboardAlbumsRouteRouteWithChildren
  '/dashboard/images': typeof DashboardImagesRouteRouteWithChildren
  '/api/proxy-image': typeof ApiProxyImageRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_chat/chat/_chatbox': typeof ChatChatChatboxRouteRouteWithChildren
  '/_general/user/$userId': typeof GeneralUserUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/task-tracker/$taskListId': typeof DashboardTaskTrackerTaskListIdRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_chat/chat/': typeof ChatChatIndexRoute
  '/_general/about/': typeof GeneralAboutIndexRoute
  '/_general/article/': typeof GeneralArticleIndexRoute
  '/_general/blog/': typeof GeneralBlogIndexRoute
  '/_general/blogposts/': typeof GeneralBlogpostsIndexRoute
  '/_general/envologs/': typeof GeneralEnvologsIndexRoute
  '/_general/post/': typeof GeneralPostIndexRoute
  '/album/$albumId/': typeof AlbumAlbumIdIndexRoute
  '/blog/$slug/': typeof BlogSlugIndexRoute
  '/blogposts/$slug/': typeof BlogpostsSlugIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/albums/': typeof DashboardAlbumsIndexRoute
  '/dashboard/blog/': typeof DashboardBlogIndexRoute
  '/dashboard/image-upload/': typeof DashboardImageUploadIndexRoute
  '/dashboard/images/': typeof DashboardImagesIndexRoute
  '/dashboard/post/': typeof DashboardPostIndexRoute
  '/dashboard/quran-tracker/': typeof DashboardQuranTrackerIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/task-tracker/': typeof DashboardTaskTrackerIndexRoute
  '/envologs/$slug/': typeof EnvologsSlugIndexRoute
  '/post/$postId/': typeof PostPostIdIndexRoute
  '/dashboard/albums/$albumId/': typeof DashboardAlbumsAlbumIdIndexRoute
  '/dashboard/blog/$slug/': typeof DashboardBlogSlugIndexRoute
  '/dashboard/blog/create-blog/': typeof DashboardBlogCreateBlogIndexRoute
  '/dashboard/blog/md-editor/': typeof DashboardBlogMdEditorIndexRoute
  '/dashboard/blog/$slug/edit/md-editor': typeof DashboardBlogSlugEditMdEditorRoute
  '/_chat/chat/_chatbox/$adapter/': typeof ChatChatChatboxAdapterIndexRoute
  '/dashboard/blog/$slug/edit/': typeof DashboardBlogSlugEditIndexRoute
  '/_chat/chat/_chatbox/$adapter/$chatId/': typeof ChatChatChatboxAdapterChatIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/chat'
    | '/dashboard/albums'
    | '/dashboard/images'
    | '/api/proxy-image'
    | '/api/uploadthing'
    | '/article/$slug'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/chat'
    | '/user/$userId'
    | '/api/auth/$'
    | '/dashboard/task-tracker/$taskListId'
    | '/login/'
    | '/chat/'
    | '/about/'
    | '/article/'
    | '/blog/'
    | '/blogposts/'
    | '/envologs/'
    | '/post/'
    | '/album/$albumId/'
    | '/blog/$slug/'
    | '/blogposts/$slug/'
    | '/dashboard/admin/'
    | '/dashboard/albums/'
    | '/dashboard/blog/'
    | '/dashboard/image-upload/'
    | '/dashboard/images/'
    | '/dashboard/post/'
    | '/dashboard/quran-tracker/'
    | '/dashboard/settings/'
    | '/dashboard/task-tracker/'
    | '/envologs/$slug/'
    | '/post/$postId/'
    | '/dashboard/albums/$albumId/'
    | '/dashboard/blog/$slug/'
    | '/dashboard/blog/create-blog/'
    | '/dashboard/blog/md-editor/'
    | '/dashboard/blog/$slug/edit/md-editor'
    | '/chat/$adapter/'
    | '/dashboard/blog/$slug/edit/'
    | '/chat/$adapter/$chatId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/proxy-image'
    | '/api/uploadthing'
    | '/article/$slug'
    | '/dashboard/profile'
    | '/dashboard'
    | '/chat'
    | '/user/$userId'
    | '/api/auth/$'
    | '/dashboard/task-tracker/$taskListId'
    | '/login'
    | '/about'
    | '/article'
    | '/blog'
    | '/blogposts'
    | '/envologs'
    | '/post'
    | '/album/$albumId'
    | '/blog/$slug'
    | '/blogposts/$slug'
    | '/dashboard/admin'
    | '/dashboard/albums'
    | '/dashboard/blog'
    | '/dashboard/image-upload'
    | '/dashboard/images'
    | '/dashboard/post'
    | '/dashboard/quran-tracker'
    | '/dashboard/settings'
    | '/dashboard/task-tracker'
    | '/envologs/$slug'
    | '/post/$postId'
    | '/dashboard/albums/$albumId'
    | '/dashboard/blog/$slug'
    | '/dashboard/blog/create-blog'
    | '/dashboard/blog/md-editor'
    | '/dashboard/blog/$slug/edit/md-editor'
    | '/chat/$adapter'
    | '/dashboard/blog/$slug/edit'
    | '/chat/$adapter/$chatId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_general'
    | '/dashboard'
    | '/api/chat'
    | '/dashboard/albums'
    | '/dashboard/images'
    | '/api/proxy-image'
    | '/api/uploadthing'
    | '/article/$slug'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/_chat/chat/_chatbox'
    | '/_general/user/$userId'
    | '/api/auth/$'
    | '/dashboard/task-tracker/$taskListId'
    | '/_auth/login/'
    | '/_chat/chat/'
    | '/_general/about/'
    | '/_general/article/'
    | '/_general/blog/'
    | '/_general/blogposts/'
    | '/_general/envologs/'
    | '/_general/post/'
    | '/album/$albumId/'
    | '/blog/$slug/'
    | '/blogposts/$slug/'
    | '/dashboard/admin/'
    | '/dashboard/albums/'
    | '/dashboard/blog/'
    | '/dashboard/image-upload/'
    | '/dashboard/images/'
    | '/dashboard/post/'
    | '/dashboard/quran-tracker/'
    | '/dashboard/settings/'
    | '/dashboard/task-tracker/'
    | '/envologs/$slug/'
    | '/post/$postId/'
    | '/dashboard/albums/$albumId/'
    | '/dashboard/blog/$slug/'
    | '/dashboard/blog/create-blog/'
    | '/dashboard/blog/md-editor/'
    | '/dashboard/blog/$slug/edit/md-editor'
    | '/_chat/chat/_chatbox/$adapter/'
    | '/dashboard/blog/$slug/edit/'
    | '/_chat/chat/_chatbox/$adapter/$chatId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GeneralRouteRoute: typeof GeneralRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiChatRouteRoute: typeof ApiChatRouteRoute
  ApiProxyImageRoute: typeof ApiProxyImageRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  ChatChatChatboxRouteRoute: typeof ChatChatChatboxRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ChatChatIndexRoute: typeof ChatChatIndexRoute
  AlbumAlbumIdIndexRoute: typeof AlbumAlbumIdIndexRoute
  BlogSlugIndexRoute: typeof BlogSlugIndexRoute
  BlogpostsSlugIndexRoute: typeof BlogpostsSlugIndexRoute
  EnvologsSlugIndexRoute: typeof EnvologsSlugIndexRoute
  PostPostIdIndexRoute: typeof PostPostIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_general': {
      id: '/_general'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GeneralRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy-image': {
      id: '/api/proxy-image'
      path: '/api/proxy-image'
      fullPath: '/api/proxy-image'
      preLoaderRoute: typeof ApiProxyImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/albums': {
      id: '/dashboard/albums'
      path: '/albums'
      fullPath: '/dashboard/albums'
      preLoaderRoute: typeof DashboardAlbumsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/images': {
      id: '/dashboard/images'
      path: '/images'
      fullPath: '/dashboard/images'
      preLoaderRoute: typeof DashboardImagesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_chat/chat/': {
      id: '/_chat/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/chat/_chatbox': {
      id: '/_chat/chat/_chatbox'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatChatChatboxRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_general/about/': {
      id: '/_general/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof GeneralAboutIndexRouteImport
      parentRoute: typeof GeneralRouteRoute
    }
    '/_general/article/': {
      id: '/_general/article/'
      path: '/article'
      fullPath: '/article/'
      preLoaderRoute: typeof GeneralArticleIndexRouteImport
      parentRoute: typeof GeneralRouteRoute
    }
    '/_general/blog/': {
      id: '/_general/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof GeneralBlogIndexRouteImport
      parentRoute: typeof GeneralRouteRoute
    }
    '/_general/blogposts/': {
      id: '/_general/blogposts/'
      path: '/blogposts'
      fullPath: '/blogposts/'
      preLoaderRoute: typeof GeneralBlogpostsIndexRouteImport
      parentRoute: typeof GeneralRouteRoute
    }
    '/_general/envologs/': {
      id: '/_general/envologs/'
      path: '/envologs'
      fullPath: '/envologs/'
      preLoaderRoute: typeof GeneralEnvologsIndexRouteImport
      parentRoute: typeof GeneralRouteRoute
    }
    '/_general/post/': {
      id: '/_general/post/'
      path: '/post'
      fullPath: '/post/'
      preLoaderRoute: typeof GeneralPostIndexRouteImport
      parentRoute: typeof GeneralRouteRoute
    }
    '/_general/user/$userId': {
      id: '/_general/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof GeneralUserUserIdRouteImport
      parentRoute: typeof GeneralRouteRoute
    }
    '/album/$albumId/': {
      id: '/album/$albumId/'
      path: '/album/$albumId'
      fullPath: '/album/$albumId/'
      preLoaderRoute: typeof AlbumAlbumIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug/': {
      id: '/blog/$slug/'
      path: '/blog/$slug'
      fullPath: '/blog/$slug/'
      preLoaderRoute: typeof BlogSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogposts/$slug/': {
      id: '/blogposts/$slug/'
      path: '/blogposts/$slug'
      fullPath: '/blogposts/$slug/'
      preLoaderRoute: typeof BlogpostsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/albums/': {
      id: '/dashboard/albums/'
      path: '/'
      fullPath: '/dashboard/albums/'
      preLoaderRoute: typeof DashboardAlbumsIndexRouteImport
      parentRoute: typeof DashboardAlbumsRouteRoute
    }
    '/dashboard/blog/': {
      id: '/dashboard/blog/'
      path: '/blog'
      fullPath: '/dashboard/blog/'
      preLoaderRoute: typeof DashboardBlogIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/image-upload/': {
      id: '/dashboard/image-upload/'
      path: '/image-upload'
      fullPath: '/dashboard/image-upload/'
      preLoaderRoute: typeof DashboardImageUploadIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/images/': {
      id: '/dashboard/images/'
      path: '/'
      fullPath: '/dashboard/images/'
      preLoaderRoute: typeof DashboardImagesIndexRouteImport
      parentRoute: typeof DashboardImagesRouteRoute
    }
    '/dashboard/post/': {
      id: '/dashboard/post/'
      path: '/post'
      fullPath: '/dashboard/post/'
      preLoaderRoute: typeof DashboardPostIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/quran-tracker/': {
      id: '/dashboard/quran-tracker/'
      path: '/quran-tracker'
      fullPath: '/dashboard/quran-tracker/'
      preLoaderRoute: typeof DashboardQuranTrackerIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/task-tracker/': {
      id: '/dashboard/task-tracker/'
      path: '/task-tracker'
      fullPath: '/dashboard/task-tracker/'
      preLoaderRoute: typeof DashboardTaskTrackerIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/task-tracker/$taskListId': {
      id: '/dashboard/task-tracker/$taskListId'
      path: '/task-tracker/$taskListId'
      fullPath: '/dashboard/task-tracker/$taskListId'
      preLoaderRoute: typeof DashboardTaskTrackerTaskListIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/envologs/$slug/': {
      id: '/envologs/$slug/'
      path: '/envologs/$slug'
      fullPath: '/envologs/$slug/'
      preLoaderRoute: typeof EnvologsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId/': {
      id: '/post/$postId/'
      path: '/post/$postId'
      fullPath: '/post/$postId/'
      preLoaderRoute: typeof PostPostIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/albums/$albumId/': {
      id: '/dashboard/albums/$albumId/'
      path: '/$albumId'
      fullPath: '/dashboard/albums/$albumId/'
      preLoaderRoute: typeof DashboardAlbumsAlbumIdIndexRouteImport
      parentRoute: typeof DashboardAlbumsRouteRoute
    }
    '/dashboard/blog/$slug/': {
      id: '/dashboard/blog/$slug/'
      path: '/blog/$slug'
      fullPath: '/dashboard/blog/$slug/'
      preLoaderRoute: typeof DashboardBlogSlugIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/blog/create-blog/': {
      id: '/dashboard/blog/create-blog/'
      path: '/blog/create-blog'
      fullPath: '/dashboard/blog/create-blog/'
      preLoaderRoute: typeof DashboardBlogCreateBlogIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/blog/md-editor/': {
      id: '/dashboard/blog/md-editor/'
      path: '/blog/md-editor'
      fullPath: '/dashboard/blog/md-editor/'
      preLoaderRoute: typeof DashboardBlogMdEditorIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_chat/chat/_chatbox/$adapter/': {
      id: '/_chat/chat/_chatbox/$adapter/'
      path: '/$adapter'
      fullPath: '/chat/$adapter/'
      preLoaderRoute: typeof ChatChatChatboxAdapterIndexRouteImport
      parentRoute: typeof ChatChatChatboxRouteRoute
    }
    '/dashboard/blog/$slug/edit/': {
      id: '/dashboard/blog/$slug/edit/'
      path: '/blog/$slug/edit'
      fullPath: '/dashboard/blog/$slug/edit/'
      preLoaderRoute: typeof DashboardBlogSlugEditIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/blog/$slug/edit/md-editor': {
      id: '/dashboard/blog/$slug/edit/md-editor'
      path: '/blog/$slug/edit/md-editor'
      fullPath: '/dashboard/blog/$slug/edit/md-editor'
      preLoaderRoute: typeof DashboardBlogSlugEditMdEditorRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_chat/chat/_chatbox/$adapter/$chatId/': {
      id: '/_chat/chat/_chatbox/$adapter/$chatId/'
      path: '/$adapter/$chatId'
      fullPath: '/chat/$adapter/$chatId/'
      preLoaderRoute: typeof ChatChatChatboxAdapterChatIdIndexRouteImport
      parentRoute: typeof ChatChatChatboxRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GeneralRouteRouteChildren {
  GeneralUserUserIdRoute: typeof GeneralUserUserIdRoute
  GeneralAboutIndexRoute: typeof GeneralAboutIndexRoute
  GeneralArticleIndexRoute: typeof GeneralArticleIndexRoute
  GeneralBlogIndexRoute: typeof GeneralBlogIndexRoute
  GeneralBlogpostsIndexRoute: typeof GeneralBlogpostsIndexRoute
  GeneralEnvologsIndexRoute: typeof GeneralEnvologsIndexRoute
  GeneralPostIndexRoute: typeof GeneralPostIndexRoute
}

const GeneralRouteRouteChildren: GeneralRouteRouteChildren = {
  GeneralUserUserIdRoute: GeneralUserUserIdRoute,
  GeneralAboutIndexRoute: GeneralAboutIndexRoute,
  GeneralArticleIndexRoute: GeneralArticleIndexRoute,
  GeneralBlogIndexRoute: GeneralBlogIndexRoute,
  GeneralBlogpostsIndexRoute: GeneralBlogpostsIndexRoute,
  GeneralEnvologsIndexRoute: GeneralEnvologsIndexRoute,
  GeneralPostIndexRoute: GeneralPostIndexRoute,
}

const GeneralRouteRouteWithChildren = GeneralRouteRoute._addFileChildren(
  GeneralRouteRouteChildren,
)

interface DashboardAlbumsRouteRouteChildren {
  DashboardAlbumsIndexRoute: typeof DashboardAlbumsIndexRoute
  DashboardAlbumsAlbumIdIndexRoute: typeof DashboardAlbumsAlbumIdIndexRoute
}

const DashboardAlbumsRouteRouteChildren: DashboardAlbumsRouteRouteChildren = {
  DashboardAlbumsIndexRoute: DashboardAlbumsIndexRoute,
  DashboardAlbumsAlbumIdIndexRoute: DashboardAlbumsAlbumIdIndexRoute,
}

const DashboardAlbumsRouteRouteWithChildren =
  DashboardAlbumsRouteRoute._addFileChildren(DashboardAlbumsRouteRouteChildren)

interface DashboardImagesRouteRouteChildren {
  DashboardImagesIndexRoute: typeof DashboardImagesIndexRoute
}

const DashboardImagesRouteRouteChildren: DashboardImagesRouteRouteChildren = {
  DashboardImagesIndexRoute: DashboardImagesIndexRoute,
}

const DashboardImagesRouteRouteWithChildren =
  DashboardImagesRouteRoute._addFileChildren(DashboardImagesRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAlbumsRouteRoute: typeof DashboardAlbumsRouteRouteWithChildren
  DashboardImagesRouteRoute: typeof DashboardImagesRouteRouteWithChildren
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTaskTrackerTaskListIdRoute: typeof DashboardTaskTrackerTaskListIdRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardBlogIndexRoute: typeof DashboardBlogIndexRoute
  DashboardImageUploadIndexRoute: typeof DashboardImageUploadIndexRoute
  DashboardPostIndexRoute: typeof DashboardPostIndexRoute
  DashboardQuranTrackerIndexRoute: typeof DashboardQuranTrackerIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardTaskTrackerIndexRoute: typeof DashboardTaskTrackerIndexRoute
  DashboardBlogSlugIndexRoute: typeof DashboardBlogSlugIndexRoute
  DashboardBlogCreateBlogIndexRoute: typeof DashboardBlogCreateBlogIndexRoute
  DashboardBlogMdEditorIndexRoute: typeof DashboardBlogMdEditorIndexRoute
  DashboardBlogSlugEditMdEditorRoute: typeof DashboardBlogSlugEditMdEditorRoute
  DashboardBlogSlugEditIndexRoute: typeof DashboardBlogSlugEditIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAlbumsRouteRoute: DashboardAlbumsRouteRouteWithChildren,
  DashboardImagesRouteRoute: DashboardImagesRouteRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTaskTrackerTaskListIdRoute: DashboardTaskTrackerTaskListIdRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardBlogIndexRoute: DashboardBlogIndexRoute,
  DashboardImageUploadIndexRoute: DashboardImageUploadIndexRoute,
  DashboardPostIndexRoute: DashboardPostIndexRoute,
  DashboardQuranTrackerIndexRoute: DashboardQuranTrackerIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardTaskTrackerIndexRoute: DashboardTaskTrackerIndexRoute,
  DashboardBlogSlugIndexRoute: DashboardBlogSlugIndexRoute,
  DashboardBlogCreateBlogIndexRoute: DashboardBlogCreateBlogIndexRoute,
  DashboardBlogMdEditorIndexRoute: DashboardBlogMdEditorIndexRoute,
  DashboardBlogSlugEditMdEditorRoute: DashboardBlogSlugEditMdEditorRoute,
  DashboardBlogSlugEditIndexRoute: DashboardBlogSlugEditIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface ChatChatChatboxRouteRouteChildren {
  ChatChatChatboxAdapterIndexRoute: typeof ChatChatChatboxAdapterIndexRoute
  ChatChatChatboxAdapterChatIdIndexRoute: typeof ChatChatChatboxAdapterChatIdIndexRoute
}

const ChatChatChatboxRouteRouteChildren: ChatChatChatboxRouteRouteChildren = {
  ChatChatChatboxAdapterIndexRoute: ChatChatChatboxAdapterIndexRoute,
  ChatChatChatboxAdapterChatIdIndexRoute:
    ChatChatChatboxAdapterChatIdIndexRoute,
}

const ChatChatChatboxRouteRouteWithChildren =
  ChatChatChatboxRouteRoute._addFileChildren(ChatChatChatboxRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GeneralRouteRoute: GeneralRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiChatRouteRoute: ApiChatRouteRoute,
  ApiProxyImageRoute: ApiProxyImageRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  ChatChatChatboxRouteRoute: ChatChatChatboxRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ChatChatIndexRoute: ChatChatIndexRoute,
  AlbumAlbumIdIndexRoute: AlbumAlbumIdIndexRoute,
  BlogSlugIndexRoute: BlogSlugIndexRoute,
  BlogpostsSlugIndexRoute: BlogpostsSlugIndexRoute,
  EnvologsSlugIndexRoute: EnvologsSlugIndexRoute,
  PostPostIdIndexRoute: PostPostIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
